metadata: >
  hydra:
    run:
      dir: ${oc.env:SCRATCH,.}/jaxmarl/outputs/mappo_rnn_overcooked_v3_full_obs/${now:%Y-%m-%d}/${now:%H-%M-%S}

  "ENV_KWARGS":
    "layout": "cramped_room"
    "agent_view_size": null
    "shaped_rewards": True
    "random_agent_positions": True
    "max_steps": 400

  "LR": 0.00025
  "ANNEAL_LR": True
  "LR_WARMUP": 0.05

  "NUM_ENVS": 256
  "NUM_STEPS": 256
  "UPDATE_EPOCHS": 4
  "NUM_MINIBATCHES": 64

  "TOTAL_TIMESTEPS": 3e7
  "REW_SHAPING_HORIZON": 1.5e7
  "SHAPED_REWARD_SCALE": 1.0

  "FC_DIM_SIZE": 64
  "GRU_HIDDEN_DIM": 128

  "CLIP_EPS": 0.2
  "ENT_COEF": 0.04
  "GAMMA": 0.99
  "GAE_LAMBDA": 0.95
  "VF_COEF": 0.5
  "MAX_GRAD_NORM": 0.5
  "ACTIVATION": "relu"
  "SEED": 0
  "NUM_SEEDS": 1

  "ENTITY": ""
  "PROJECT": ""
  "WANDB_MODE": "disabled"
  "WANDB_RUN_NAME": ""
  "WANDB_DIR": "${oc.env:SCRATCH,.}/jaxmarl/mappo_overcooked_v3_full_obs"
  "USE_RICH_MONITOR": True

hydra:
  run:
    dir: ${oc.env:SCRATCH,.}/jaxmarl/outputs/mappo_rnn_overcooked_v3_full_obs/${now:%Y-%m-%d}/${now:%H-%M-%S}

"ENV_KWARGS":
  "layout": "button_gated_zones"
  "agent_view_size": null
  "shaped_rewards": True
  "random_agent_positions": True
  "max_steps": 400

# Optimization & Learning Scaling
"LR": 0.0003                      # Scaled up to account for the larger global batch size
"ANNEAL_LR": True
"LR_WARMUP": 0.05

# --- THE EFFICIENCY ENGINE (4GB VRAM-SAFE) ---
"NUM_ENVS": 128                  # Halved from 256 to fit CNN gradients into 4GB
"NUM_STEPS": 128
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4             # Halved from 8. Minibatch size remains (128 * 128) / 4 = 4,096

"TOTAL_TIMESTEPS": 6e7
"REW_SHAPING_HORIZON": 3e7
"SHAPED_REWARD_SCALE": 1.0

"FC_DIM_SIZE": 64
"GRU_HIDDEN_DIM": 128

"CLIP_EPS": 0.2
"ENT_COEF": 0.08      # UPDATED FOR GATED ZONES
"GAMMA": 0.995        # UPDATED FOR GATED ZONES                     
"GAE_LAMBDA": 0.95                 
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"SEED": 0
"NUM_SEEDS": 1

"ENTITY": "zach-tang-university-of-toronto"
"PROJECT": "button-gated-zones-mappo-full-obs"
"WANDB_MODE": "online"
"WANDB_RUN_NAME": "button_gated_zones_mappo_full_obs"
"WANDB_DIR": "${oc.env:SCRATCH,.}/jaxmarl/mappo_overcooked_v3_full_obs"
"USE_RICH_MONITOR": True