#!/usr/bin/env bash
# QMIX on coordinated_temporal_conveyor, mirroring the WINNING around_the_island recipe.
#   around params: NUM_ENVS=4, NUM_STEPS=400=max_steps (full-episode BPTT), BUFFER 512/32,
#                  order_generation_rate=1.0, order_expiration_time=0, alternating queue,
#                  SHAPED_REWARD_COEFF=2.5, TEST off, full obs.
#   kept from session: Huber loss (in code), NUM_EPOCHS=8, NO L2 distance shaping.
#   map-specific: conveyors ON (this is a conveyor map).
set -euo pipefail

tmux new-session -d -s jaxmarl_qmix_ctc_6m_cogridpots_sharedobs_ws_20260629 "cd /student/brownd58/dev/JaxMARL && export PYTHONPATH=/student/brownd58/dev/JaxMARL:\${PYTHONPATH:-} && export PATH=/student/brownd58/dev/JaxMARL/.venv/lib/python3.10/site-packages/nvidia/cuda_nvcc/bin:\$PATH && export XLA_PYTHON_CLIENT_MEM_FRACTION=0.99 && mkdir -p /student/brownd58/dev/JaxMARL/outputs /student/brownd58/dev/JaxMARL/checkpoints && PYTHONUNBUFFERED=1 /student/brownd58/dev/JaxMARL/.venv/bin/python /student/brownd58/dev/JaxMARL/baselines/QLearning/qmix_rnn.py +alg=ql_rnn_overcooked_v3 WANDB_MODE=online PROJECT=ocv3_qlearning_coordinated_temporal_conveyor +alg.WANDB_NAME=qmix_ctc_6m_cogridpots_sharedobs_ws_20260629 ENTITY=zacharytang24- SEED=42 +alg.LOAD_PATH=/student/brownd58/dev/JaxMARL/checkpoints/qmix_ctc_6m_cogridpots_dense_20260627/overcooked_v3_coordinated_temporal_conveyor/qmix_rnn_overcooked_v3_coordinated_temporal_conveyor_seed42_vmap0.safetensors SAVE_PATH=/student/brownd58/dev/JaxMARL/checkpoints/qmix_ctc_6m_cogridpots_sharedobs_ws_20260629 +alg.SAVE_GIF_PATH=/student/brownd58/dev/JaxMARL/outputs/qmix_ctc_6m_cogridpots_sharedobs_ws_20260629.gif +alg.GIF_NUM_STEPS=400 alg.ENV_KWARGS.layout=coordinated_temporal_conveyor alg.ENV_KWARGS.agent_view_size=null alg.ENV_KWARGS.max_steps=400 alg.ENV_KWARGS.pot_cook_time=60 alg.ENV_KWARGS.pot_burn_time=90 alg.ENV_KWARGS.enable_order_queue=true alg.ENV_KWARGS.max_orders=5 alg.ENV_KWARGS.order_generation_rate=1.0 alg.ENV_KWARGS.order_expiration_time=0 alg.ENV_KWARGS.recipe_mode=fixed +alg.ENV_KWARGS.plate_pickup_guard=1 alg.ENV_KWARGS.enable_item_conveyors=true alg.ENV_KWARGS.enable_player_conveyors=false alg.TOTAL_TIMESTEPS=6000000 alg.NUM_ENVS=4 alg.NUM_STEPS=400 alg.BUFFER_SIZE=512 alg.BUFFER_BATCH_SIZE=32 alg.HIDDEN_SIZE=256 alg.MIXER_EMBEDDING_DIM=64 alg.MIXER_HYPERNET_HIDDEN_DIM=256 alg.MIXER_INIT_SCALE=0.001 alg.EPS_START=1.0 alg.EPS_FINISH=0.05 alg.EPS_DECAY=0.2 alg.MAX_GRAD_NORM=10 alg.TARGET_UPDATE_INTERVAL=10 alg.TAU=1.0 alg.NUM_EPOCHS=8 alg.LR=0.00005 alg.LEARNING_STARTS=10000 alg.LR_LINEAR_DECAY=false alg.GAMMA=0.99 alg.REW_SCALE=1.0 alg.SHAPED_REWARD_COEFF=1.0 alg.REW_SHAPING_HORIZON=6000000 alg.REW_SHAPING_MIN_COEFF=1.0 alg.TEST_DURING_TRAINING=false > /student/brownd58/dev/JaxMARL/outputs/qmix_ctc_6m_cogridpots_sharedobs_ws_20260629_train.log 2>&1"
