#!/usr/bin/env bash
# IPPO-RNN on around_the_island using the IDENTICAL params from the superior reference run
#   bld6tz9b (overcookedv3_ippo_rnn_around_the_island_order_visible_plateguard_burn40_20260606_181720):
#   max_steps=1000, SHAPED_REWARD_COEFF=30, ENT_COEF=0.01, REW_SHAPING_HORIZON=15M (kept identical),
#   REW_SHAPING_MIN_COEFF=0.1, alternating queue, gen_rate=1, expiration=0, burn40/cook20, guard default(1).
# ONLY deviation: TOTAL_TIMESTEPS=6M (not the reference's 15M), as requested.
# Logged to the same wandb project as the recent CTC runs.
set -euo pipefail

tmux new-session -d -s jaxmarl_ippo_ctc_6m_refparams_20260627 "cd /student/brownd58/dev/JaxMARL && export PATH=/student/brownd58/dev/JaxMARL/.venv/lib/python3.10/site-packages/nvidia/cuda_nvcc/bin:\$PATH && PYTHONUNBUFFERED=1 /student/brownd58/dev/JaxMARL/.venv/bin/python /student/brownd58/dev/JaxMARL/baselines/IPPO/ippo_rnn_overcooked_v3.py --config-name=ippo_rnn_overcooked_v3 WANDB_MODE=online WANDB_PROJECT=ocv3_qlearning_coordinated_temporal_conveyor WANDB_NAME=ippo_ctc_6m_refparams_coeff30_ent01_ms1000_20260627 ENTITY=zacharytang24- ENV_KWARGS.layout=coordinated_temporal_conveyor ENV_KWARGS.max_steps=1000 ENV_KWARGS.pot_cook_time=20 ENV_KWARGS.pot_burn_time=40 ENV_KWARGS.enable_order_queue=true ENV_KWARGS.max_orders=5 ENV_KWARGS.order_generation_rate=1.0 ENV_KWARGS.order_expiration_time=0 ENV_KWARGS.order_queue_mode=alternating ENV_KWARGS.plate_pickup_guard=1 ENV_KWARGS.enable_item_conveyors=true ENV_KWARGS.enable_player_conveyors=false TOTAL_TIMESTEPS=6000000 NUM_ENVS=128 NUM_STEPS=200 UPDATE_EPOCHS=4 NUM_MINIBATCHES=8 LR=0.0005 GAMMA=0.99 GAE_LAMBDA=0.95 CLIP_EPS=0.2 VF_COEF=0.5 ENT_COEF=0.01 ENT_COEF_MIN=0.0 ENTROPY_FLOOR=0.0 ENTROPY_FLOOR_COEF=0.0 MAX_GRAD_NORM=0.5 GRU_HIDDEN_DIM=128 FC_DIM_SIZE=128 ACTIVATION=relu ANNEAL_LR=true REW_SHAPING_HORIZON=15000000 REW_SHAPING_MIN_COEFF=0.1 SHAPED_REWARD_COEFF=30 SEED=42 SAVE_PATH=/student/brownd58/dev/JaxMARL/checkpoints/ippo_ctc_6m_refparams_20260627 SAVE_GIF_PATH=/student/brownd58/dev/JaxMARL/outputs/ippo_ctc_6m_refparams_20260627.gif LOG_EVERY=1 CHECKPOINT_EVERY=5000 > /student/brownd58/dev/JaxMARL/outputs/ippo_ctc_6m_refparams_20260627_train.log 2>&1"
